# Generated by Django 4.2.5 on 2023-11-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_card', models.CharField(max_length=12)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
